[env:esp32-p4]
platform = espressif32
board = esp32-p4
; Khai báo dùng song song cả 2 framework để tận dụng idf_component.yml
framework = arduino, espidf
lib_deps =
	https://github.com/moononournation/Arduino_GFX.git
	bblanchon/ArduinoJson@^7.0.4
lib_extra_dirs = /media/covanan/data/Wokr/KisGroup/ESP32-P4-86PANEL-ETH-2RO/Arduino/libraries

build_flags = 
    -I/media/covanan/data/Wokr/KisGroup/ESP32-P4-86PANEL-ETH-2RO/Arduino/libraries
    -I/media/covanan/data/Wokr/KisGroup/ESP32-P4-86PANEL-ETH-2RO/Arduino/libraries/lvgl
    -D LV_CONF_INCLUDE_SIMPLE
    -D ARDUINO_AS_COMPONENT
    -D BOARD_HAS_PSRAM
    ; Cờ này giúp bỏ qua các lỗi lặt vặt của LVGL với trình biên dịch mới
    -Wno-error
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
